In [214]:
# Two routes: Laplacian Eigenmaps and hierarchical clustering
#eventually fix
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [215]:
import numpy as np
import pandas as pd
from sklearn.cluster import SpectralClustering
USERNAME = 'pleasedshibe1'
similarity_matrix = np.load(f'../{USERNAME}_similarity_matrix.npy')
df = pd.read_csv(f'../{USERNAME}finished.csv')
#round?
print(similarity_matrix)
df.drop('Unnamed: 0', axis=1, inplace=True)


distmtx = []
for i, row in enumerate(similarity_matrix):
    distrow = []
    for j, value in enumerate(row):
        if i == j:
            distrow.append(0)
        else:
            distrow.append(1 - value)
    distmtx.append(distrow)
    

[[1.         0.4898244  0.48881844 ... 0.48863577 0.46422369 0.44435199]
 [0.4898244  1.         0.48583382 ... 0.4934435  0.4805344  0.46105408]
 [0.48881844 0.48583382 1.         ... 0.48318537 0.46383119 0.44413869]
 ...
 [0.48863577 0.4934435  0.48318537 ... 1.         0.4785969  0.46517838]
 [0.46422369 0.4805344  0.46383119 ... 0.4785969  1.         0.46492857]
 [0.44435199 0.46105408 0.44413869 ... 0.46517838 0.46492857 1.        ]]


In [216]:
distmtx

[[0,
  0.5101755955334462,
  0.5111815629321714,
  0.69980510475091,
  0.6001143049733737,
  0.9998769734331406,
  0.5658452086616633,
  0.5084027750729274,
  0.5611117028185333,
  0.5418532713046806,
  0.5116361094372353,
  0.5076585907817003,
  0.537963141620243,
  0.5148150171906847,
  0.5445864990099332,
  0.5247630935816412,
  0.51678307212468,
  0.6336244789631489,
  0.5204189961742829,
  0.519235089869178,
  0.9998769734331406,
  0.5190578646165793,
  0.5265030874573466,
  0.5200036345546588,
  0.5433260274683157,
  0.517697405135149,
  0.5134601390424038,
  0.5196389936788809,
  0.5737867272335122,
  0.5534903938802389,
  0.5229045722974442,
  0.5542742210940781,
  0.509957727947506,
  0.5290507561935487,
  0.6685103126720486,
  0.5250236052621401,
  0.5120335957297634,
  0.5668505893599336,
  0.5284092020461405,
  0.516914086784319,
  0.5562472415171524,
  0.5569488988389584,
  0.5056934818359191,
  0.5045762849897747,
  0.5076602147984051,
  0.5050950606750131,
  0.5124529189

In [217]:
df.iloc[89]

username                                                     Echomist2
name                                                      🌱 Echomist 🌱
description          Hiya! ❤️ Banner by Kofe Australian Female 17 D...
number of tweets                                                   511
followers                                                          134
verified                                                         False
tweets               "7 ft frame, rats along his black. When he cal...
links                [['https://www.fiverr.com/share/k5QXQw'], ['ht...
hashtags             ['warriorcats', 'adoptable', 'art', 'bearsmp',...
interacting users    ['Echomist2', 'DSMPYELLOW', 'Echomist2', 'Noir...
Name: 89, dtype: object

In [218]:
len(similarity_matrix)

from sklearn.cluster import DBSCAN
dbscan_clusters = DBSCAN(eps=0.5, min_samples=5, metric='precomputed', metric_params=None, algorithm='auto', leaf_size=30, p=None, n_jobs=None).fit_predict(distmtx)


In [219]:
df['Dcluster'] = dbscan_clusters

In [220]:
dbscan_clusters

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [221]:
df.loc[df['Dcluster'] == 2]

Empty DataFrame
Columns: [username, name, description, number of tweets, followers, verified, tweets, links, hashtags, interacting users, Dcluster]
Index: []

In [222]:
from gensim import corpora, models, similarities
import pyLDAvis.gensim_models as gensim_models

import pyLDAvis
pyLDAvis.enable_notebook()

ldamodel = models.LdaModel.load('../lda.model')
import pickle
with open ('../corpus.ob', 'rb') as fp:
    corpus = pickle.load(fp)


In [223]:
ldamodel.id2word

In [224]:
vis = pyLDAvis.gensim_models.prepare(ldamodel, corpus, dictionary=ldamodel.id2word)
vis

/home/liam_mckenna/.local/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/liam_mckenna/.local/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/liam_mckenna/.local/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/liam_mckenna/.local/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
/home/liam_mckenna/.local/lib/python3.8/site-packages/past/builtins/misc.py:45: 

PreparedData(topic_coordinates=              x         y  topics  cluster       Freq
topic                                                
2     -0.022724 -0.000377       1        1  29.080580
5      0.004837 -0.010506       2        1  12.615279
6      0.004588  0.005265       3        1  11.717728
3      0.004330  0.003098       4        1  11.348456
4      0.001137  0.001427       5        1  11.049585
1      0.003032  0.000557       6        1   8.951266
0      0.002799  0.000359       7        1   8.405372
7      0.002001  0.000176       8        1   6.831735, topic_info=                  Term       Freq      Total Category  logprob  loglift
598           nebbiiee  65.000000  65.000000  Default  30.0000  30.0000
10263     like_youtube   8.000000   8.000000  Default  29.0000  29.0000
6858           deytral   6.000000   6.000000  Default  28.0000  28.0000
4357      pleasedshibe  10.000000  10.000000  Default  27.0000  27.0000
32651  evan_does_tweet   4.000000   4.000000  Default  26.0000  26.0000
...                ...        ...        ...      ...      ...      ...
10054            viral   0.017070   0.674051   Topic8 -10.4636  -0.9924
36973          optoute   0.016178   0.517746   Topic8 -10.5173  -0.7822
33529         sunexist   0.017397   1.245836   Topic8 -10.4447  -1.5877
12515    pj_switchstop   0.018826   4.118638   Topic8 -10.3657  -2.7045
9468           dribzrl   0.017518   1.701166   Topic8 -10.4378  -1.8923

[292 rows x 6 columns], token_table=       Topic      Freq            Term
term                                  
19356      1  0.862013        ashleyjk
25586      8  1.088795      autorasuck
2106       3  1.342800      benjimenrl
1144       1  0.845754          bestie
38330      1  0.854135  biscosupremacy
...      ...       ...             ...
7385       2  0.749544      wooloolove
35859      1  0.616739        yoonsjim
30573      4  0.599020      yuckygrape
11498      5  0.816905         zapynub
2075       8  0.885107  zetexkindasuck

[124 rows x 3 columns], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[3, 6, 7, 4, 5, 2, 1, 8])